### ISSUE TITLE
1d please 

### ISSUE THREAD

**Issue by danFromTelAviv** [deconvolutionpaper/deconvolution#3]
Hi, 
I bet this would also work for speech recognition and signal processing. maybe even nlp and algo trading. 
I would love to try this out for speech recognition tasks in particular. 
Can you please generate a 1d devonvolution class. Seems like it shouldn't be too difficult - especially if you really understand every line of code you wrote... 

Thanks
Dan

**Comment by danFromTelAviv** [comment]
also  - if I already have your attention - is the deconvolution in your implementation local or global. Does the pixel get information about "future" steps (as it would from batch norm) or only the same receptive field as the convolutions?

**Comment by yechengxi** [comment]
Currently there is no plan for the 1d development as I do not have a project at hand. The deconvolution is local.

**Comment by danFromTelAviv** [comment]
ok. thanks for the frank reply. 
thats very interesting ( in the 1 d world at leat ). 
have a great day.
