### ISSUE TITLE
Implementation details

### ISSUE THREAD

**Issue by titu1994** [deconvolutionpaper/deconvolution#4]
First, let me congratulate you on your paper and also thank you for open-sourcing the code. I was porting the deconv operations/layers to Tensorflow and was wondering about something.

1) Is the [deconv covariance buffer](https://github.com/yechengxi/deconvolution/blob/master/models/deconv.py#L262) the vast majority of non-trainable parameters in your models? Practically speaking, without groups (which Tensorflow doesn't support easily), the cost for that matrix in terms of parameters = `[K1 * K2 * num_blocks] ^ 2`. For a 3x3 kernel with 64 blocks, that's roughly 330K parameters right there. Are grouped convolutions the only remedy to this parameter explosion? It might become a network bandwidth issue in multi-node distributed training setups.

2) Under what circumstances would one prefer the [Delinear](https://github.com/yechengxi/deconvolution/blob/master/models/deconv.py#L158) implementation over the `FastDeconv` implementation?

Edit: It seems the link to the paper in the readme is broken.

**Comment by yechengxi** [comment]
The grouping should be supported in tf as long as you can reshape the tensor. When k1*k2*num_channels is big, we reshape the data matrix to achieve the grouping.

Delinear = ChannelDeconv + linear, not for replacing FastDeconv.

**Comment by titu1994** [comment]
Thanks for the clarification.
