### ISSUE TITLE
FastDeconv breaks when no bias is used

### ISSUE THREAD

**Issue by mpaepper** [deconvolutionpaper/deconvolution#9]
When setting bias = False in the constructor to FastDeconv, then the forward pass fails at:

```b = self.bias - (w @ (X_mean.unsqueeze(1))).view(self.weight.shape[0], -1).sum(1)```

This is because self.bias will be None and this line breaks.

I guess this would be possible:
```
if self.bias is None:
    b = - (w @ (X_mean.unsqueeze(1))).view(self.weight.shape[0], -1).sum(1)
else:
    b = self.bias - (w @ (X_mean.unsqueeze(1))).view(self.weight.shape[0], -1).sum(1)
```

When using Conv2d with BatchNorm, usually no bias is used in the Conv2d. However, when replacing both, then I guess a bias is needed again. So I'm not sure if there are useful cases for not using a bias when using the FastDeconv?

Thanks for the paper and the implementation!

**Comment by yechengxi** [comment]
Yes, this is the correct implementation. We can keep  bias=True because in normal networks the bias is moved from conv to BN.

**Comment by mpaepper** [comment]
Maybe it would be better to force it then and ignore the value of the constructor?

Otherwise it's confusing, because it breaks, when you call it with bias=False
